USE [DBA_MONITOR]
GO
CREATE TABLE [dbo].[RESULTADO_SHOWINDEX](
	[DATE_COLLECTION] [datetime] NOT NULL,
	[SERVER_NAME] [varchar](200) NULL,
	[DATABASE_NAME] [varchar](200) NULL,
	[TABLE_NAME] [varchar](200) NULL,
	[INDEX_NAME] [varchar](200) NULL,
	[INDEX_TYPE] [varchar](30) NULL,
	[SEEKS] [bigint] NOT NULL,
	[SCANS] [bigint] NOT NULL,
	[LOOKUPS] [bigint] NOT NULL,
	[UPDATES] [bigint] NOT NULL,
	[PAGE_COUNT] [bigint] NOT NULL,
	[ROW_COUNT] [bigint] NOT NULL,
	[FILL_FACTOR] [tinyint] NULL,
	[DATA_COMPRESSION] [varchar](60) NOT NULL,
	[AVG_FRAGMENTATION_IN_PERCENT] [decimal](18, 0) NULL,
	[COLUMNS] [varchar](max) NULL,
	[INCLUDE_COLUMNS] [varchar](max) NOT NULL,
	[PRIMARY_KEY] [int] NULL,
	[LAST_SEEK] [datetime] NULL,
	[LAST_SCAN] [datetime] NULL,
	[LAST_LOOKUP] [datetime] NULL,
	[LAST_UPDATE] [datetime] NULL,
	[IS_DISABLED] [varchar](3) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE CLUSTERED INDEX IDX_RESULTADO_SHOWINDEX ON RESULTADO_SHOWINDEX(DATE_COLLECTION,SERVER_NAME,DATABASE_NAME,TABLE_NAME,INDEX_NAME,INDEX_TYPE)
GO




SELECT * FROM [RESULTADO_SHOWINDEX]